[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Recipes"
  weight = 20
  identifier = "recipes"
  url = "/docs/recipes/"

[[docs]]
  name = "Reference Guides"
  weight = 30
  identifier = "reference-guides"
  url = "/docs/reference-guides/"

[[docs]]
  name = "Extensions"
  weight = 40
  identifier = "extensions"
  url = "/docs/extensions/"

[[docs]]
  name = "Contributing"
  weight = 50
  identifier = "contributing"
  url = "/docs/contributing/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

[[main]]
  name = "Who We Are"
  url = "/about/"
  weight = 10

[[main]]
  name = "Solutions"
  url = "/solutions/"
  weight = 20

[[main]]
  name = "News & Insights"
  url = "/blog/"
  weight = 30

[[main]]
  name = "Careers"
  url = "/careers/"
  weight = 40

#[[main]]
 # name = "Community"
 # url = "https://github.com/h-enk/hyas/discussions"
 # weight = 50

# [[footer]]
#   name = "Community"
#   url = "https://github.com/h-enk/hyas/discussions"
#   weight = 30

[[showcase]]
  name = "Browse"
  weight = 10
  identifier = "browse"
  url = "/showcase/"

[[secondary]]
  name = "Submit to Themes"
  url = "https://github.com/h-enk/hyas/discussions?discussions_q=category%3A%22Show+and+tell%22"
  weight = 10

[[themes]]
  name = "Browse"
  weight = 10
  identifier = "browse"
  url = "/themes/"

[[tertiary]]
  name = "Submit to Showcase"
  url = "https://github.com/h-enk/hyas/discussions?discussions_q=category%3A%22Show+and+tell%22"
  weight = 10
